### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by 10urbulut** [VB10/Dart-Language-Full-Course#2]
Veli bey selamlar, nasılsınız? 
Sizi youtube ve google dsc eğitimlerinden biliyorum. 

Ben flutter upgrade yaptıktan sonra bu hatayı almaya başladım. Google search yaptım çözüm olarak karşıma çıkan her şeyi denedim. flutter clean, paketlerin vesiyonları, compileSdk versiyonu, kotlin versiyonu, pub cahce repair, jdk sürümü yükselttim,tekrar downgrade yaptım olmadı, aynı hata devam ediyor. Belki de ben yaptıklarımı düzgün yapamadım. Son çare sizin issue lara bakıyorum dediğiniz aklıma geldi o yüzden buradayım. 
Umarım günlerdir savaştığım şu sorununun çözümü sizdedir, teşekkürler şimdiden :)

![image](https://user-images.githubusercontent.com/77685360/155879555-c4a5bc9e-6842-495c-b323-36785cdfb437.png)

Launching lib\main.dart on SM N750 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
D:\OnurYedek\order_and_stock_flutter\order_and_stock_management\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:19: error: package id.kakzaki.blue_thermal_printer does not exist
      flutterEngine.getPlugins().add(new id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin());
                                                                        ^
D:\OnurYedek\order_and_stock_flutter\order_and_stock_management\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:24: error: package com.dexterous.flutterlocalnotifications does not exist
      flutterEngine.getPlugins().add(new com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin());
                                                                                ^
D:\OnurYedek\order_and_stock_flutter\order_and_stock_management\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:29: error: package io.github.ponnamkarthik.toast.fluttertoast does not exist
      flutterEngine.getPlugins().add(new io.github.ponnamkarthik.toast.fluttertoast.FlutterToastPlugin());
                                                                                   ^
D:\OnurYedek\order_and_stock_flutter\order_and_stock_management\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:34: error: package io.flutter.plugins.pathprovider does not exist
      flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
                                                                        ^
D:\OnurYedek\order_and_stock_flutter\order_and_stock_management\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:39: error: package io.flutter.plugins.sharedpreferences does not exist
      flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
                                                                             ^
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 27s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by uluibrahim** [comment]
Merhaba, öncelikle gradle sürümünüzü yükseltmelisiniz
android/gradle/wrapper/gradle-wrapper.properties 

`distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip
`
android/build.gradle 

`buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.android.tools.build:gradle:7.0.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
`

**Comment by 10urbulut** [comment]
> Merhaba, öncelikle gradle sürümünüzü yükseltmelisiniz android/gradle/wrapper/gradle-wrapper.properties
> 
> `distributionBase=GRADLE_USER_HOME distributionPath=wrapper/dists zipStoreBase=GRADLE_USER_HOME zipStorePath=wrapper/dists distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip ` android/build.gradle
> 
> `buildscript { ext.kotlin_version = '1.6.10' repositories { google() mavenCentral() }
> 
> ```
> dependencies {
>     classpath 'com.google.gms:google-services:4.3.10'
>     classpath 'com.android.tools.build:gradle:7.0.2'
>     classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> }
> ```
> 
> } `

Malesef işe yaramadı
